# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClusterCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClusterCommand.proto',
  package='user_cluster',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x43lusterCommand.proto\x12\x0cuser_cluster\",\n\x0e\x43lusterCommand\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLUSTERCOMMAND = _descriptor.Descriptor(
  name='ClusterCommand',
  full_name='user_cluster.ClusterCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='user_cluster.ClusterCommand.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='user_cluster.ClusterCommand.data', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['ClusterCommand'] = _CLUSTERCOMMAND

ClusterCommand = _reflection.GeneratedProtocolMessageType('ClusterCommand', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERCOMMAND,
  __module__ = 'ClusterCommand_pb2'
  # @@protoc_insertion_point(class_scope:user_cluster.ClusterCommand)
  ))
_sym_db.RegisterMessage(ClusterCommand)


# @@protoc_insertion_point(module_scope)
